import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Credit Card OTP Verfication Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{
        marginTop: 20,
        marginLeft: 'auto',
        marginRight: 'auto',
        padding: 5,
        width: 250,
        borderWidth: 1,
        borderColor: '#000',
        borderStyle: 'solid',
        height: 500,
        overflowY: 'scroll'
      }}>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex corrupti quibusdam, modi molestias neque eos quis accusamus nam expedita veniam enim quia asperiores in dolore ea? Sed laboriosam illum beatae maiores nisi esse ea autem harum suscipit repellat, tempore illo numquam quod eius dolorum tenetur sapiente quis soluta unde magnam?</p>
        <table>
          <tr>
            <th>
              name
            </th>
            <th>
              value
            </th>
          </tr>
          <tr>
            <td>xpaww</td>
            <td>xpaww</td>
          </tr>
          <tr>
            <td>xpaww</td>
            <td>xpaww</td>
          </tr>
          <tr>
            <td>xpaww</td>
            <td>xpaww</td>
          </tr>
          <tr>
            <td>xpaww</td>
            <td>xpaww</td>
          </tr>
        </table>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum est, fuga id minima consequuntur temporibus totam? Voluptate ipsa quibusdam fugiat!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur, ducimus explicabo. Amet, ea blanditiis dolore debitis recusandae laudantium beatae vero nisi sequi rerum ducimus cum vel. Ratione expedita doloremque, placeat quaerat accusamus tempore possimus, ullam exercitationem repudiandae assumenda ducimus similique nihil quos dolor vel illum error voluptatem quis asperiores et?</p>
      </main>
    </div>
  )
}
